# model
name: "codex_ibot"
vocab: ['CD66', 'CD31', 'CD227', 'CD11c', 'CD16', 'CD163', 'PDL1', 'CD123', 'CD47', 'CD141', 'CD38', 'HLA-DR', 'Caveolin1', 'HLA-ABC', 'CD66b', 'CD68', 'CXCL13', 'CD20', 'CD57', 'Tryptase', 'VISTA', 'CD117', 'CD49', 'PGP9.5', 'CXCR5', 'CD11b', 'CD138', 'ICOS', 'CD208', 'GranzymeB', 'XCR1', 'PanCK', 'INOS', 'CD8', 'BCL6', 'Gal3', 'CD14', 'bCatenin', 'Vimentin', 'HLA-E', 'Siglec8', 'CD207', 'CollagenIV', 'TFAM', 'S100A4', 'PD1', 'Keratin19', 'HistoneH3p', 'TCF1', 'TP63', 'CD194', 'TOX', 'TMEM16A', 'CD40', 'CD152', 'RORgammaT', 'Keratin14', 'CD45RO', 'IFNg', 'TIM3', 'GATA3', 'DAPI', 'CD44', 'CD34', 'CD1c', 'Clusterin', 'CD196', 'TIGIT', 'CD39', 'CD183', 'Tbet', 'CD3e', 'CD21', 'PNAD', 'CD69', 'LAG3', 'CD15', 'MPO', 'aSMA', 'CD45', 'CD25', 'Ki67', 'Podoplanin', 'CD4', 'BCL2', 'FAP', 'ATM', 'CD45RA', 'CD79', 'ECad', 'PCNA', 'EpCAM', 'CD56', 'CD19', 'p16', 'Perlecan', 'CD197', 'TCRgammadelta', 'CD206', 'IDO1', 'CD127', 'CD107a', 'ERa', 'CD134', 'CD209', 'FoxP3'] # all possible channels in dataset
nhead: 6
num_layers: 6
codex_dim: 768
mask_ratio: 0.5  # Ratio of masked patches
teacher_temperature: 0.07  
student_temperature: 0.1  
momentum: 0.996 # momemntum for teacher updates
text_model: 'microsoft/BiomedNLP-BiomedBERT-base-uncased-abstract-fulltext'
