# model
  name: "codex_text"
  marker_groups: 2 #number of different groupings, must equal data config 'channel_groups'
  text_model: 'microsoft/BiomedNLP-BiomedBERT-base-uncased-abstract-fulltext'
  codex_dim: 384
  text_dim: 768
  projection_dim: 512
  shared_projection: False
