# model
name: "trimodal"
vocab: ["S100A4", "CD16", "Perforin", "Olig2", "FAP", "CollagenIV", "CD15", "TIM3", "CD207", "CD25", "PDL1", "Vimentin", "CD38", "CD62L", "RORgammaT", "Siglec8", "PD1", "pSTAT3", "CD49", "CD107a", "CD127", "CD14", "CD140b", "CD20", "CD152", "CD56", "TFAM", "ICOS", "CD138", "F4_80", "p16", "Gal3", "ERa", "CD206", "IFNg", "XCR1", "BCL2", "Keratin8_18", "EpCAM", "CD134", "CD79", "ECad", "CD44", "CD57", "Tbet", "CD183", "HLA-ABC", "INOS", "GranzymeB", "PNAD", "DAPI", "CD31", "CD197", "PanCK", "Clusterin", "HLA-E", "CD69", "Nestin", "CD66", "PGP9.5", "CD34", "GATA3", "CD40", "CD19", "VISTA", "FoxP3", "CD45", "Caveolin1", "CD45RA", "BCL6", "CD11b", "CD117", "CD3e", "CD163", "MPO", "IDO1", "CD47", "LYVE1", "CD39", "TCRgammadelta", "LAG3", "bCatenin", "CD137", "Keratin14", "PCNA", "Podoplanin", "HistoneH3p", "TIGIT", "CXCL13", "CD45RO", "ATM", "CD196", "Ki67", "CD90", "CD66b", "CX3CR1", "CD33", "SOX10", "TCF1", "CD123", "CD11c", "TOX", "CD4", "aSMA", "CD8", "CD209", "CD141", "Perlecan", "CD227", "Tryptase", "CD21", "CXCR5", "CD194", "TMEM16A", "CD1c", "CD68", "HLA-DR", "CD208", "Keratin19", "TP63"]
nhead: 6
num_layers: 6
channel_embedding_model: 'resnet'
text_model: 'microsoft/BiomedNLP-BiomedBERT-base-uncased-abstract-fulltext'
codex_dim: 768
text_dim: 768
he_dim: 768
projection_dim: 512
shared_projection: False
load_from_pt: False
pt_model_path: None