defaults:
  - _self_
  - dataset: default
  - model: trimodal
  - training: base
  - loss: base
  - evaluation: patch_linear_probe


wandb:
  project_name: 'codex-text'
  run_name: 'test_run_resnet'

